const data = [
    {
        id: 1,
        name: "Aradhona",
        seats: 30,
        from: "Kolkata",
        to: "Barasat",
        depart_time: "9:30 am",
        arrival_time: "11:30 am",
        seat: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ]
    },
    {
        id: 2,
        name: "Salimar",
        seats: 30,
        from: "Sealdah",
        to: "Howrah",
        depart_time: "12:30 pm",
        arrival_time: "2:30 pm",
        seat: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ]
    },
    {
        id: 3,
        name: "Rajanna",
        seats: 30,
        from: "Kolkata",
        to: "Kalyani",
        depart_time: "7:30 pm",
        arrival_time: "11:30 am",
        seat: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ]
    },
    {
        id: 4,
        name: "Ragini",
        seats: 30,
        from: "Kanchrapara",
        to: "Kalyani",
        depart_time: "4:30 pm",
        arrival_time: "6:30 pm",
        seat: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        ]
    }
]

export default data